version: "3"
services:
  # Proxy (Don't touch this!)
  traefik:
    image: traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=php73"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.ws.address=:6002"
    networks:
      - php73
    ports:
      - "80:80"
      - "8080:8080"
      - "6002:6002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # App
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
    image: devstack/php73
    environment:
      WWWUSER: "${WWWUSER:-1000}"
    volumes:
      - '.:/var/www/html'
    networks:
      - php73
    depends_on:
      - mysql
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`php73.localhost`)"
      - "traefik.docker.network=php73"
  # Databases
  mysql:
    image: "mysql/mysql-server:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - '${APP_FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "php73-mysql:/var/lib/mysql"
    networks:
      - php73
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "php73-redis:/data"
    networks:
      - php73
  memcached:
    image: "memcached:alpine"
    ports:
      - "11211:11211"
    networks:
      - php73
networks:
  php73:
    driver: bridge
volumes:
  php73-mysql:
    driver: local
  php73-redis:
    driver: local